#!/bin/bash

#пацанчик ты походу не понял, в чей код ты лезешь. твоя манера лазанья тут меня не устраивает. 
#давай я обьясню тебе всё на понятном тебе языке. на python




case $USER in
	root)
		echo
	;;

	*)
		echo ошибка: недостаточно прав для запуска tvspkg
		exit 2
	;;

esac


exec 4>/dev/null

case $1 in

debug)
#exec 2>/dev/null
shift
;;
*)
exec 2>/dev/null
;;
esac

echo tvspkg v1 by tvs_
echo
case $1 in

	-i)
		
		echo скачивание пакета...
		
		rm -r $2 >&4
		
		if git clone http://github.com/tvsclass/$2 >&4 ;
			
			then echo
			
			cd $2
			
			unzip -d ./.$2 ./$2.tvs
			
			cd ./.$2
			
			echo установить $2 '(y/n)'?
			read ans 
			case $ans in
			y)
			echo
			;;
			*)
			echo операция отменена пользователем.
			exit 0
			;;
			
			esac
			
			if find iscript.sh;
				then sh iscript.sh;
				
				else 
					echo iscript.sh не найден. автоматическая установка...
					if find bin;
						then
						
						echo копирование shell части...
						pwd
						aaa=$(cat ./bin/bafl)
						cp -r bin /usr/
						chmod +x /usr/bin/$aaa;
					fi
					if find run.sh;
						then 
						echo запуск установщика...
						sh run.sh;
					fi
						
					echo инструкции выполнены.
					cd ..
					rm -r ./.$2
					rm -r ./$2.tvs 
				
				echo;
				#echo ошибка пакета. проверьте целостность пакета.;
			cd ..
			rm -r $2
			fi
			
			echo;
			
			else echo Возникла ошибка при обращении к git. проверьте соединение.
			exit 1;
			
		fi
		
		
	
	;;

	-l)
			echo распаковка пакета...
			unzip -o -d ./.$2 ./$2.tvs
			echo установить $2 '(y/n)'?
			cd ./.$2
			read ans
			case $ans in
			y)
			echo
			;;
			*)
			echo операция отменена пользователем.
			cd ..
			rm -r ./.$2;
			exit 0
			;;
			
			esac
			
			if find iscript.sh;
				then sh iscript.sh
				cd ..
				rm -r ./.$2;
				
				else 
					echo iscript.sh не найден. автоматическая установка...
					if find bin;
						then
						
						echo копирование shell части...
						pwd
						
						
						aaa=$(cat ./bin/bafl)
						cp -r bin /usr/
						chmod +x /usr/bin/$aaa;
						
						if find bafl2;
							then
							aaa=$(cat ./bin/bafl2)
							cp -r bin /usr/
							chmod +x /usr/bin/$aaa;
						fi
						if find bafl2;
							then
							aaa=$(cat ./bin/bafl3)
							cp -r bin /usr/
							chmod +x /usr/bin/$aaa;
						fi
						if find bafl2;
							then
							aaa=$(cat ./bin/bafl4)
							cp -r bin /usr/
							chmod +x /usr/bin/$aaa;
						fi
						if find bafl2;
							then
							aaa=$(cat ./bin/bafl5)
							cp -r bin /usr/
							chmod +x /usr/bin/$aaa;
						fi
						if find bafl2;
							then
							aaa=$(cat ./bin/bafl6)
							cp -r bin /usr/
							chmod +x /usr/bin/$aaa;
						fi
						
						
						
						
						
						
					fi
					if find run.sh;
						then 
						echo запуск установщика...
						sh run.sh;
					fi
						
					echo инструкции выполнены.
					cd ..
					rm -r ./.$2;
			fi
	;;

	*)
		echo опция не найдена.
		echo
		echo опции:
		echo
		echo -l локальный пакет 
		echo -i интернет пакет
	;;


esac
